apiVersion: v1
kind: ConfigMap
metadata:
  name: announcement-text
  namespace: repcal
data:
  announcement.txt: |
    Mes chers sans-culottes,

    My most sincere apologies for the recent and sudden changes to this service that have caused downtime. Hosting issues forced me to change domains,
    until I can restore my old domain, https://sansculottid.es, the French Republican Calendar can be found at https://frenchrepubilcan.info.

    But I also come bearing good news. The French Republican Calendar is now a standard.site,
    any responses to the bot (https://bsky.app/profile/frenchrepublican.info) will be recorded on that date's page.
    Please be sure to follow on BlueSky or any other app using AT Proto.

    Liberté, égalité, fraternité!
---
apiVersion: batch/v1
kind: Job
metadata:
  name: announcement
  namespace: repcal
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
      - name: announcement
        image: tupperward/repcal:announcement
        imagePullPolicy: Always
        command: ["python", "announcement.py"]
        env:
        - name: ANNOUNCEMENT_FILE
          value: /data/announcement.txt
        - name: ANNOUNCEMENT_IMAGE_URL
          value: 'https://frenchrepublican.info/static/images/revolution.jpg'
        volumeMounts:
        - name: announcement-text
          mountPath: /data/announcement.txt
          subPath: announcement.txt
      volumes:
      - name: announcement-text
        configMap:
          name: announcement-text
      restartPolicy: Never
