---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rbh-discord
  namespace: repcal
spec:
  timeZone: "America/New_York"
  schedule: '0 8 * * * '
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: discord-webhook
              image: tupperward/repcal:webhook
              imagePullPolicy: Always
              env:
              - name: "DISCORD_WEBHOOK_URL"
                value: 'https://discord.com/api/webhooks/1345290726879264899/pNJGAKztR5IJ23tu2gN01E9ZgkmCx4PNyzIH6Ri8UfzjGs_3Pg5Px8DJqIo9jWUAW6eF'
              volumeMounts:
              - name: repcal-db
                mountPath: /data
          volumes:
          - name: repcal-db
            persistentVolumeClaim:
              claimName: repcal-db
          restartPolicy: Never