# Generated by Django 3.2.9 on 2021-11-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=200)),
                ('month_of', models.CharField(max_length=200)),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('sansculottides', models.BooleanField()),
                ('item', models.CharField(max_length=200)),
                ('item_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LastTen',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=200)),
                ('month_of', models.CharField(max_length=200)),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('sansculottides', models.BooleanField()),
                ('item', models.CharField(max_length=200)),
                ('item_url', models.CharField(max_length=200)),
            ],
        ),
    ]
